-- Create Database Tables for Purchase Order Approval Workflow System

-- Drop tables if they exist (for easy re-runs)
DROP TABLE IF EXISTS approval_history CASCADE;
DROP TABLE IF EXISTS purchase_orders CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- 1. Users Table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL CHECK (role IN ('REQUESTER', 'APPROVER', 'ADMIN')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 2. Purchase Orders Table
CREATE TABLE purchase_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_number VARCHAR(50) UNIQUE NOT NULL,
    title VARCHAR(150) NOT NULL,
    description TEXT,
    vendor_name VARCHAR(150) NOT NULL,
    amount DECIMAL(15, 2) NOT NULL CHECK (amount >= 0),
    created_by BIGINT REFERENCES users(id) ON DELETE RESTRICT,
    status VARCHAR(50) NOT NULL CHECK (status IN ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 3. Approval History Table
CREATE TABLE approval_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT REFERENCES purchase_orders(id) ON DELETE CASCADE,
    approver_id BIGINT REFERENCES users(id) ON DELETE RESTRICT,
    action VARCHAR(50) NOT NULL,
    comments TEXT,
    action_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Sample Data (Optional, but useful to verify setup)
INSERT INTO users (name, email, password, role) VALUES 
('Alice Requester', 'alice@example.com', 'password123', 'REQUESTER'),
('Bob Approver', 'bob@example.com', 'password123', 'APPROVER'),
('Charlie Admin', 'charlie@example.com', 'password123', 'ADMIN');
