spring.application.name=po-approval-system

# Supabase PostgreSQL Connection configuration
# Configured to use environment variables with fallback defaults pointing to cloud Supabase instance
spring.datasource.url=${DB_URL:jdbc:postgresql://db.qsnelbxwprotsndwkiak.supabase.co:5432/postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:sandy@supabase}
spring.datasource.driver-class-name=org.postgresql.Driver

# JWT Custom Secret configuration
jwt.secret=${JWT_SECRET:30m5IRsJcGdHv6gsPNB9YGn/k+EpUUA8TE8BFG6D9J7CkmjTRNxTcmvcugQXE1eph/6XiJBwqZrfX97gcc+X4g==}


# JPA/Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Server port configuration
server.port=8080
